---
protocol: "http"
port: 8080

worker_pool:
  workers: 10
  backend: "redis"
  redis_pool:
    redis_url: "redis://harbor-redis:6379/0"
    namespace: "harbor_job_service"

job_loggers:
  - name: "FILE"
    level: "INFO"
    settings:
      base_dir: "/var/log/jobs"
    sweeper:
      duration: 1 #days
      settings:
        work_dir: "/var/log/jobs"

  - name: "STD_OUTPUT"
    level: "INFO"

logger:
  path: "/var/log/jobs"
  level: "INFO"
  archive_period: 14 #days

core:
  url: "http://harbor-core:8080"
  token_service_url: "http://harbor-core:8080/service/token"

job_service_secret: "harbor-jobservice-secret"
