appname = harbor-core
runmode = prod

[dev]
httpport = 8080

[prod]
httpport = 8080

[database]
type = postgresql
host = harbor-db
port = 5432
username = harbor7
password = harbor7
database = registry
sslmode = disable

[core]
secret = key111
harbor_admin_password = Harbor12345
harbor_url = http://harbor-portal:80
token_expiration = 30
max_job_workers = 10
absolute_url = false
audit_log_forward_endpoint =

[cache]
type = memory
expiration = 30
key = harbor-cache-key
memory_size = 128

[jobservice]
url = http://harbor-jobservice:8080
webhook_job_max_retry = 10
verify_remote_cert = false

[log]
level = info
local_location = /var/log/harbor
rotate_count = 50
rotate_size = 200M
rotate_time = 24h
log_level = debug
